apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: pradeep11


secretGenerator:
- name: mysql-pass
  literals:
  - password=lw@123


resources:
- nmspace.yml
- efs_provisioner.yml
- rolebinding.yml
- storage.yml
- mysql1.yml
- wordpress1.yml