apiVersion: v1
kind: Service   
metadata:
  name: database1
  labels:
    app: database1
  namespace: pradeep11
spec:
  ports:
    - port: 3306
  selector:
    app: database1
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: database1
  labels:
    app: database1
  namespace: pradeep11
spec:
  replicas: 3
  selector:
    matchLabels:
      app: database1
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database1
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: "webpage"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: efs-mysql  