kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: web-efs
  namespace: pradeep11
provisioner: ma/web-efs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-mysql
  annotations:
    volume.beta.kubernetes.io/storage-class: "web-efs"
  namespace: myekscluster12
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-web
  annotations:
    volume.beta.kubernetes.io/storage-class: "web-efs"
  namespace: pradeep11
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
       
      storage: 10Gi