apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: WebServer
  namespace: pradeep11
spec:
  ports:
    - port: 80
  selector:
    app: WebServer
    tier: front-end
  type: LoadBalancer
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: webserver
  labels:
    app: WebServer
  namespace: pradeep11
spec:
  replicas: 5
  selector:
    matchLabels:
      app: WebServer
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: WebServer
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: webserver
        ports:
        - containerPort: 80
          name: webserver
        volumeMounts:
        - name: webserver-persistent
          mountPath: /var/www/html
      volumes:
      - name: webserver-persistent
        persistentVolumeClaim:
          claimName: efs-web
